### ISSUE TITLE
Cannot get route if config if route.root is '/' and routes begin with '/'

### ISSUE THREAD

**Issue by Couapy** [vigilock/fast-custom-router#4]
**Describe the bug**
Cannot get route if config if route.root is '/' and routes begin with '/'.

Get : `Cannot GET url_here`

**To Reproduce**
```yaml
root:
  root: /
  pre_middlewares:
    - basic:urlencoder
    - basic:bodyParser_
    - basic:cors_
    - logRequests
  routes:
    api:
      root: /api/global/v1
      post_middlewares:
        - unknownRoute
        - errorHandler
      routes:
        import:
          - api/channel.yaml
          - api/user.yaml

```
